project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!ROADMAP.md"

website:
  title: "Social and Public health"
  site-url: "index.qmd"

  navbar:
    left:
      - text: "Contents"
        href: intro.qmd
      - text: "Topic Index"
        href: topic-index.qmd
      - text: "Foundations"
        menu:
          - text: "Man and Medicine: Towards Health for All"
            href: foundations/man-and-medicine.qmd
          - text: "Concept of Health and Disease"
            href: foundations/concept-health-disease.qmd
          - text: "Principles of Epidemiology"
            href: foundations/principles-epidemiology.qmd
          - text: "Epidemiologic Methods"
            href: foundations/epidemiologic-methods.qmd
          - text: "Screening for Disease"
            href: foundations/screening.qmd
      - text: "CDs and NCDs"
        menu:
          - text: "Epidemiology of Communicable Diseases"
            href: diseases/communicable-diseases.qmd
          - text: "Selected Diseases: Overview"
            href: diseases/cd.qmd
          - text: "Module 1: Malaria"
            href: diseases/cd/module1_malaria.qmd
          - text: "Module 2: Typhoid Fever & Cholera"
            href: diseases/cd/module2_typhoid_cholera.qmd
          - text: "Module 3: Viral Hepatitis"
            href: diseases/cd/module3_viral_hepatitis.qmd
          - text: "Module 4: Poliomyelitis"
            href: diseases/cd/module4_poliomyelitis.qmd
          - text: "Module 5: Food Poisoning & Diarrhoeal Disease"
            href: diseases/cd/module5_food_poisoning.qmd
          - text: "Module 6: Hospital-Acquired Infections"
            href: diseases/cd/module6_hospital_acquired_infections.qmd
          - text: "Epidemiology of Chronic Non-Communicable Diseases"
            href: diseases/ncd.qmd
          - text: "Essential Medicines and Counterfeit Medicines"
            href: diseases/essential-medicines.qmd
          - text: "Nutrition and Health"
            href: diseases/nutrition.qmd
          - text: "Mental Health"
            href: diseases/mental-health.qmd
      - text: "Pragrams & demography"
        menu:
          - text: "Health Programmes in India"
            href: programs/health-programmes.qmd
          - text: "Millennium Development Goals to Sustainable Development Goals"
            href: programs/mdg-sdg.qmd
          - text: "Demography and Family Planning"
            href: programs/demography.qmd
          - text: "Preventive Medicine in Obstetrics, Paediatrics and Geriatrics"
            href: programs/preventive-medicine.qmd
          - text: "Tribal Health in India"
            href: programs/tribal-health.qmd
      - text: "Environment"
        menu:
          - text: "Environment and Health"
            href: environment/environment-health.qmd
          - text: "One Health"
            href: environment/env_health/module1_one_health.qmd
          - text: "Environment & Health Components"
            href: environment/env_health/module2_environment_health.qmd
          - text: "Water and Health"
            href: environment/env_health/water.qmd
          - text: "Hospital Waste Management"
            href: environment/waste-management.qmd
          - text: "Disaster Management"
            href: environment/disaster-management.qmd
          - text: "Occupational Health"
            href: environment/occupational-health.qmd
          - text: "Genetics and Health"
            href: environment/genetics.qmd
      - text: "Miscellaneous"
        menu:
          - text: "Health Information and Basic Medical Statistics"
            href: global/health-information.qmd
          - text: "Communication for Health Education"
            href: global/health-education.qmd
          - text: "Medicine and Social Sciences"
            href: global/social-sciences.qmd
          - text: "Health Planning and Management"
            href: global/health-planning.qmd
          - text: "Health Care of the Community"
            href: global/community-health.qmd
          - text: "International Health"
            href: global/international-health.qmd
      - text: "Post Graduate"
        menu:
          - text: "Guide for Dissertation"
            href: post_graduate/dissertation-guide.qmd
          
      
    right:
      - text: "Reference"
        icon: book
        menu:
          - text: "Contact Us"
            href: assets/contact.qmd
          - text: "References"
            href: assets/references.qmd

  sidebar:
    style: "docked"
    collapse: true
    search: true
    contents:
      - section: "Foundations of Health & Epidemiology"
        contents:
          - text: "Man and Medicine: Towards Health for All"
            file: foundations/man-and-medicine.qmd
          - text: "Concept of Health and Disease"
            file: foundations/concept-health-disease.qmd
          - text: "Principles of Epidemiology"
            file: foundations/principles-epidemiology.qmd
          - text: "Epidemiologic Methods"
            file: foundations/epidemiologic-methods.qmd
          - text: "Screening for Disease"
            file: foundations/screening.qmd

      - section: "Communicable & Non-Communicable Diseases"
        contents:
          - text: "Epidemiology of Communicable Diseases"
            file: diseases/communicable-diseases.qmd
          - section: "Selected Communicable Diseases"
            contents:
              - text: "Overview"
                file: diseases/cd.qmd
              - text: "Module 1: Malaria"
                file: diseases/cd/module1_malaria.qmd
              - text: "Module 2: Typhoid Fever & Cholera"
                file: diseases/cd/module2_typhoid_cholera.qmd
              - text: "Module 3: Viral Hepatitis"
                file: diseases/cd/module3_viral_hepatitis.qmd
              - text: "Module 4: Poliomyelitis"
                file: diseases/cd/module4_poliomyelitis.qmd
              - text: "Module 5: Food Poisoning & Diarrhoeal Disease"
                file: diseases/cd/module5_food_poisoning.qmd
              - text: "Module 6: Hospital-Acquired Infections"
                file: diseases/cd/module6_hospital_acquired_infections.qmd
          - text: "Epidemiology of Chronic Non-Communicable Diseases"
            file: diseases/ncd.qmd
          - text: "Essential Medicines and Counterfeit Medicines"
            file: diseases/essential-medicines.qmd
          - text: "Nutrition and Health"
            file: diseases/nutrition.qmd
          - text: "Mental Health"
            file: diseases/mental-health.qmd

      - section: "Health Programs & Populations"
        contents:
          - text: "Health Programmes in India"
            file: programs/health-programmes.qmd
          - text: "Millennium Development Goals to Sustainable Development Goals"
            file: programs/mdg-sdg.qmd
          - text: "Demography and Family Planning"
            file: programs/demography.qmd
          - text: "Preventive Medicine in Obstetrics, Paediatrics and Geriatrics"
            file: programs/preventive-medicine.qmd
          - text: "Tribal Health in India"
            file: programs/tribal-health.qmd

      - section: "Environment, Systems & Emergencies"
        contents:
          - section: "Environment and Health"
            contents:
              - text: "Overview"
                file: environment/environment-health.qmd
              - text: "One Health"
                file: environment/env_health/module1_one_health.qmd
              - text: "Environment & Health Components"
                file: environment/env_health/module2_environment_health.qmd
              - section: "Water and Health"
                contents:
                  - text: "Overview"
                    file: environment/env_health/water.qmd
                  - text: "Water Quality Standards"
                    file: environment/env_health/water/module3_water_quality.qmd
                  - text: "Water Sources"
                    file: environment/env_health/water/module4_water_sources.qmd
                  - text: "Treatment"
                    file: environment/env_health/water/module5_water_treatment.qmd
                  - text: "Pollution & Diseases"
                    file: environment/env_health/water/module6_pollution_diseases.qmd
                  - text: "Surveillance"
                    file: environment/env_health/water/module7_surveillance.qmd
                  - text: "Safe Water in India"
                    file: environment/env_health/water/module8_safe_water_india.qmd
                  - text: "Quiz"
                    file: environment/env_health/water/module9_quiz.qmd
          - text: "Hospital Waste Management"
            file: environment/waste-management.qmd
          - text: "Disaster Management"
            file: environment/disaster-management.qmd
          - text: "Occupational Health"
            file: environment/occupational-health.qmd
          - text: "Genetics and Health"
            file: environment/genetics.qmd

      - section: "Health Information, Education & Global Perspectives"
        contents:
          - text: "Health Information and Basic Medical Statistics"
            file: global/health-information.qmd
          - text: "Communication for Health Education"
            file: global/health-education.qmd
          - text: "Medicine and Social Sciences"
            file: global/social-sciences.qmd
          - text: "Health Planning and Management"
            file: global/health-planning.qmd
          - text: "Health Care of the Community"
            file: global/community-health.qmd
          - text: "International Health"
            file: global/international-health.qmd

format:
  html:
    theme: flatly
    css: assets/theme_webp.css
    code-copy: true
    toc: true
    lightbox: auto